### PR TITLE
MSYS-547: [win32-certstore] Verify Certificate

### PR DESCRIPTION
**Pull request by piyushawasthi**
**Note:** First merge PR: #16 after that need to rebase this branch.

**Description:**
This method verify certificate using thumbprint and return boolean.

**Usages:**
```
thumbprint = "‎75 e0 ab b6 13 85 12 27 1c 04 f8 5f dd de 38 e4 b7 24 2e fe"
Win32::Certstore.open("ROOT") do |store|
  cert_obj = store.verify("‎75 e0 ab b6 13 85 12 27 1c 04 f8 5f dd de 38 e4 b7 24 2e fe")
  store.close
end
```
**Return:**.
```
True
```

### CODE REVIEW

**Comment by btm** [comment]
@piyushawasthi can you rebase this and make the shell_out changes similar to #19 please?

**Comment by piyushawasthi** [comment]
Hi @btm , This branch is rebased and shell_out changes done. Also fixed failing test-cases and tested manually. So this is ready to merge.

**Comment by btm** [comment]
It's hard to tell what the methods here do exactly. For example, I think I would name the `valid_duration`  method `valid_duration?` instead, which would indicate to me that it's going to return true or false. Similarly name `verify` something like `valid_certificate?`.

We should probably start adding YaRD documentation to the library to be more formally explicit about the methods. http://www.rubydoc.info/gems/yard/file/docs/GettingStarted.md 

I'll probably make a separate chore card to go back around and do that on code we've already committed.

**Comment by piyushawasthi** [comment]
Hi @btm - I have update the method name `vaild_certificate?(certificate_thumbprint)`. Please correct me if I am wrong for better understanding I think all method should be look similar.
for example either we keep method names as:
```
store.add(certificate_obj)
store.get(certificate_thumbprint)
store.list(certstore_handler)
store.delete(certificate_thumbprint)
store.search(certificate_name)
store.valid?(certificate_thumbprint)
```
OR
```
store.add_certificate(certificate_obj)
store.get_certificate(certificate_thumbprint)
store.list_certificates
store.delete_certificate(certificate_thumbprint)
store.search_certificate(certificate_name)
store.valid_certificate?(certificate_thumbprint)
```
Please let me know your thought about it.

**Comment by btm** [comment]
@piyushawasthi I remember thinking about this a while ago, but I forget what we were thinking. The first thing to come to mind was `store.add` sounds like I'm adding a certificate store, not a cert. Secondly, `certificate` feels like a word that's going to be easy to misspell, although I had no problem typing it just now. But maybe `add_cert` is a better pattern. Either way.

**Pull request merged**
